-- Только для отдельной тестовой базы clinic_course_test. Скрипт удаляет и создаёт таблицы.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =====================================================================
--  Поликлиника — БД в 3НФ (PostgreSQL)
--  Запуск: выполнить скрипт целиком в пустой базе
-- =====================================================================

DROP VIEW  IF EXISTS v_invoice CASCADE;
DROP TABLE IF EXISTS audit, prescription, referral, visit_service, invoice,
                     visit, appointment, schedule, account, patient, employee,
                     service, drug, diagnosis, pay_method, service_group,
                     role, room, post, specialty CASCADE;

-- ---------------------------------------------------------------------
--  СПРАВОЧНИКИ
-- ---------------------------------------------------------------------
CREATE TABLE specialty (
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE
);

CREATE TABLE post (                       -- должность
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE
);

CREATE TABLE room (                       -- кабинет
    id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number varchar(10) NOT NULL UNIQUE,
    floor  smallint    NOT NULL
);

CREATE TABLE role (
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL UNIQUE
);

CREATE TABLE service_group (              -- категория услуги
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL UNIQUE
);

CREATE TABLE pay_method (                 -- способ оплаты
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(30) NOT NULL UNIQUE
);

CREATE TABLE diagnosis (                  -- справочник МКБ-10
    code varchar(10)  PRIMARY KEY,
    name varchar(300) NOT NULL
);

CREATE TABLE drug (                       -- лекарства
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) NOT NULL UNIQUE
);

CREATE TABLE service (                    -- прайс услуг
    id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id integer       NOT NULL REFERENCES service_group(id),
    name     varchar(200)  NOT NULL UNIQUE,
    price    numeric(10,2) NOT NULL CHECK (price >= 0),
    is_active boolean      NOT NULL DEFAULT true
);

-- ---------------------------------------------------------------------
--  ЛЮДИ
-- ---------------------------------------------------------------------
CREATE TABLE employee (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name   varchar(50) NOT NULL,
    first_name  varchar(50) NOT NULL,
    middle_name varchar(50),
    post_id     integer     NOT NULL REFERENCES post(id),
    specialty_id integer    REFERENCES specialty(id),
    phone       varchar(20),
    is_active   boolean     NOT NULL DEFAULT true
);

CREATE TABLE patient (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_number  varchar(20)  NOT NULL UNIQUE,
    last_name    varchar(50)  NOT NULL,
    first_name   varchar(50)  NOT NULL,
    middle_name  varchar(50),
    birth_date   date         NOT NULL,
    gender       char(1)      NOT NULL CHECK (gender IN ('М','Ж')),
    snils        varchar(14)  UNIQUE,
    oms_policy   varchar(16)  NOT NULL UNIQUE,
    dms_policy   varchar(20)  UNIQUE,
    address      varchar(200),
    phone        varchar(20),
    created_date date         NOT NULL DEFAULT CURRENT_DATE,
    is_active    boolean      NOT NULL DEFAULT true
);

CREATE TABLE account (                    -- учётная запись
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login         varchar(50)  NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL,
    role_id       integer      NOT NULL REFERENCES role(id),
    employee_id   integer      UNIQUE REFERENCES employee(id),
    patient_id    integer      UNIQUE REFERENCES patient(id),
    is_active     boolean      NOT NULL DEFAULT true,
    last_login    timestamp,
    -- учётка принадлежит либо сотруднику, либо пациенту
    CHECK ((employee_id IS NULL) <> (patient_id IS NULL))
);

-- Настройка интерфейса привязана к учётной записи.
CREATE TABLE user_theme (
    account_id integer PRIMARY KEY REFERENCES account(id) ON DELETE CASCADE,
    theme varchar(5) NOT NULL DEFAULT 'light' CHECK (theme IN ('light', 'dark')),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
--  РАСПИСАНИЕ И ЗАПИСЬ
-- ---------------------------------------------------------------------
CREATE TABLE schedule (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id   integer  NOT NULL REFERENCES employee(id),
    room_id       integer  NOT NULL REFERENCES room(id),
    work_date     date     NOT NULL,
    start_time    time     NOT NULL,
    end_time      time     NOT NULL,
    slot_minutes  integer  NOT NULL CHECK (slot_minutes > 0),
    UNIQUE (employee_id, work_date),
    CHECK (end_time > start_time)
);

CREATE TABLE appointment (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id integer     NOT NULL REFERENCES schedule(id),
    patient_id  integer     NOT NULL REFERENCES patient(id),
    start_time  time        NOT NULL,
    status      varchar(20) NOT NULL DEFAULT 'запланирована'
                CHECK (status IN ('запланирована','завершена','отменена','неявка')),
    source      varchar(20) NOT NULL
                CHECK (source IN ('регистратура','телефон','сайт','приложение')),
    created_at  timestamp   NOT NULL DEFAULT now(),
    UNIQUE (schedule_id, start_time)      -- один слот — одна запись
);

-- ---------------------------------------------------------------------
--  ПРИЁМ
-- ---------------------------------------------------------------------
CREATE TABLE visit (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id  integer   NOT NULL UNIQUE REFERENCES appointment(id),
    visited_at      timestamp NOT NULL,
    complaints      text,
    anamnesis       text,
    objective_status text,
    diagnosis_code  varchar(10) REFERENCES diagnosis(code),
    recommendations text,
    is_closed       boolean   NOT NULL DEFAULT false
);

-- ---------------------------------------------------------------------
--  ОПЛАТА
--  total в счёте не хранится (это производное значение) — см. v_invoice
-- ---------------------------------------------------------------------
CREATE TABLE invoice (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id integer     NOT NULL REFERENCES patient(id),
    created_at timestamp   NOT NULL DEFAULT now(),
    status     varchar(20) NOT NULL DEFAULT 'не оплачен'
               CHECK (status IN ('не оплачен','оплачен','отменён')),
    method_id  integer     REFERENCES pay_method(id),
    paid_at    timestamp,
    CHECK ((status = 'оплачен') = (paid_at IS NOT NULL)),
    CHECK (status <> 'оплачен' OR method_id IS NOT NULL)
);

CREATE TABLE visit_service (              -- оказанные услуги
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id    integer       NOT NULL REFERENCES visit(id),
    service_id  integer       NOT NULL REFERENCES service(id),
    invoice_id  integer       REFERENCES invoice(id),
    quantity    integer       NOT NULL DEFAULT 1 CHECK (quantity > 0),
    price       numeric(10,2) NOT NULL CHECK (price >= 0),  -- цена на момент оказания
    rendered_at timestamp     NOT NULL
);

-- ---------------------------------------------------------------------
--  НАПРАВЛЕНИЯ И НАЗНАЧЕНИЯ (дата выдачи = дата приёма, отдельно не хранится)
-- ---------------------------------------------------------------------
CREATE TABLE referral (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id    integer     NOT NULL REFERENCES visit(id),
    service_id  integer     NOT NULL REFERENCES service(id),
    status      varchar(20) NOT NULL DEFAULT 'выдано'
                CHECK (status IN ('выдано','выполнено','отменено')),
    executor_id integer     REFERENCES employee(id),
    done_at     timestamp,
    result      text
);

CREATE TABLE prescription (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id    integer      NOT NULL REFERENCES visit(id),
    drug_id     integer      NOT NULL REFERENCES drug(id),
    dosage      varchar(100),
    instruction text,
    is_recipe   boolean      NOT NULL DEFAULT false   -- true = рецептурный
);

-- ---------------------------------------------------------------------
--  ЖУРНАЛ ДЕЙСТВИЙ
-- ---------------------------------------------------------------------
CREATE TABLE audit (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id integer     NOT NULL REFERENCES account(id),
    patient_id integer     REFERENCES patient(id),
    acted_at   timestamp   NOT NULL DEFAULT now(),
    action     varchar(20) NOT NULL CHECK (action IN ('SELECT','INSERT','UPDATE','DELETE')),
    table_name varchar(50) NOT NULL,
    record_id  integer
);

-- ---------------------------------------------------------------------
--  ИНДЕКСЫ ПО ВНЕШНИМ КЛЮЧАМ
-- ---------------------------------------------------------------------
CREATE INDEX ix_employee_specialty ON employee(specialty_id);
CREATE INDEX ix_schedule_date      ON schedule(work_date);
CREATE INDEX ix_appointment_patient ON appointment(patient_id);
CREATE INDEX ix_visit_diagnosis    ON visit(diagnosis_code);
CREATE INDEX ix_invoice_patient    ON invoice(patient_id);
CREATE INDEX ix_vs_visit           ON visit_service(visit_id);
CREATE INDEX ix_vs_invoice         ON visit_service(invoice_id);
CREATE INDEX ix_referral_visit     ON referral(visit_id);
CREATE INDEX ix_prescription_visit ON prescription(visit_id);
CREATE INDEX ix_audit_account      ON audit(account_id);
CREATE INDEX ix_audit_patient      ON audit(patient_id);

-- ---------------------------------------------------------------------
--  ПРЕДСТАВЛЕНИЕ: счёт с рассчитанной суммой
-- ---------------------------------------------------------------------
CREATE VIEW v_invoice AS
SELECT i.id,
       i.patient_id,
       i.created_at,
       i.status,
       i.method_id,
       i.paid_at,
       COALESCE(SUM(vs.quantity * vs.price), 0)::numeric(10,2) AS total
FROM invoice i
LEFT JOIN visit_service vs ON vs.invoice_id = i.id
GROUP BY i.id;

-- =====================================================================
--  ТЕСТОВЫЕ ДАННЫЕ
-- =====================================================================
INSERT INTO specialty (id, name) VALUES
 (1,'Терапия'),(2,'Кардиология'),(3,'Неврология'),
 (4,'Офтальмология'),(5,'Хирургия'),(6,'Лабораторная диагностика');

INSERT INTO post (id, name) VALUES
 (1,'Врач'),(2,'Заведующий отделением'),(3,'Лаборант'),
 (4,'Администратор регистратуры'),(5,'Системный администратор');

INSERT INTO room (id, number, floor) VALUES
 (1,'101',1),(2,'102',1),(3,'103',1),(4,'104',1),
 (5,'201',2),(6,'202',2),(7,'203',2);

INSERT INTO role (id, name) VALUES
 (1,'Администратор'),(2,'Врач'),(3,'Регистратор'),(4,'Лаборант'),(5,'Пациент');

INSERT INTO service_group (id, name) VALUES
 (1,'Приём'),(2,'Анализы'),(3,'Диагностика'),(4,'Процедуры');

INSERT INTO pay_method (id, name) VALUES
 (1,'Наличные'),(2,'Банковская карта'),(3,'СБП');

INSERT INTO diagnosis (code, name) VALUES
 ('J06.9','Острая инфекция верхних дыхательных путей неуточнённая'),
 ('J20.9','Острый бронхит неуточнённый'),
 ('I10','Эссенциальная (первичная) гипертензия'),
 ('G43.9','Мигрень неуточнённая'),
 ('H52.1','Миопия'),
 ('K29.7','Гастрит неуточнённый'),
 ('M54.5','Боль внизу спины');

INSERT INTO drug (id, name) VALUES
 (1,'Амоксициллин'),(2,'Парацетамол'),(3,'Лозартан'),(4,'Амлодипин'),
 (5,'Суматриптан'),(6,'Омепразол'),(7,'Амброксол'),(8,'Ибупрофен'),(9,'Тауфон');

INSERT INTO service (id, group_id, name, price, is_active) VALUES
 (1, 1,'Приём терапевта первичный',        1800.00, true),
 (2, 1,'Приём кардиолога первичный',       2500.00, true),
 (3, 1,'Приём невролога первичный',        2400.00, true),
 (4, 1,'Приём офтальмолога первичный',     2200.00, true),
 (5, 1,'Приём хирурга первичный',          2300.00, true),
 (6, 2,'Общий анализ крови',                450.00, true),
 (7, 2,'Биохимический анализ крови',       1200.00, true),
 (8, 2,'Общий анализ мочи',                 300.00, true),
 (9, 2,'Тест на Helicobacter pylori',       650.00, true),
 (10,3,'ЭКГ',                               900.00, true),
 (11,3,'УЗИ брюшной полости',              1900.00, true),
 (12,3,'Рентген грудной клетки',           1300.00, true),
 (13,3,'МРТ головного мозга',             5200.00, true),
 (14,4,'Подбор очков',                      600.00, true),
 (15,4,'Внутримышечная инъекция',           250.00, true),
 (16,4,'Электрофорез',                      600.00, false);

INSERT INTO employee (id, last_name, first_name, middle_name, post_id, specialty_id, phone, is_active) VALUES
 (1,'Соколов',  'Андрей',   'Викторович',  2, 1,    '+7 (495) 123-45-01', true),
 (2,'Иванова',  'Елена',    'Петровна',    1, 2,    '+7 (495) 123-45-02', true),
 (3,'Кузнецов', 'Дмитрий',  'Олегович',    1, 3,    '+7 (495) 123-45-03', true),
 (4,'Морозова', 'Ольга',    'Сергеевна',   1, 4,    '+7 (495) 123-45-04', true),
 (5,'Волков',   'Игорь',    'Николаевич',  1, 5,    '+7 (495) 123-45-05', true),
 (6,'Лебедева', 'Марина',   'Александровна',3,6,    '+7 (495) 123-45-06', true),
 (7,'Петрова',  'Анна',     'Игоревна',    4, NULL, '+7 (495) 123-45-07', true),
 (8,'Орлов',    'Сергей',   'Павлович',    5, NULL, '+7 (495) 123-45-08', true),
 (9,'Смирнова', 'Наталья',  'Юрьевна',     1, 1,    '+7 (495) 123-45-09', true);

INSERT INTO patient (id, card_number, last_name, first_name, middle_name, birth_date, gender,
                     snils, oms_policy, dms_policy, address, phone, created_date, is_active) VALUES
 (1,'П-000001','Кириллов', 'Максим',   'Андреевич',   '1985-03-14','М','112-233-445 95','7701234500000001','ДМС-100201','г. Москва, ул. Профсоюзная, д. 12, кв. 45',      '+7 (916) 111-22-33','2026-01-15',true),
 (2,'П-000002','Захарова', 'Ирина',    'Владимировна','1992-07-21','Ж','123-456-789 01','7701234500000002',NULL,        'г. Москва, ул. Академика Янгеля, д. 5, кв. 12', '+7 (925) 222-33-44','2026-02-03',true),
 (3,'П-000003','Никитин',  'Павел',    'Сергеевич',   '1978-11-02','М','234-567-890 12','7701234500000003','ДМС-100203','г. Москва, Варшавское ш., д. 88, кв. 101',     '+7 (903) 333-44-55','2025-11-20',true),
 (4,'П-000004','Фёдорова', 'Алина',    'Дмитриевна',  '2001-01-30','Ж','345-678-901 23','7701234500000004',NULL,        'г. Москва, ул. Днепропетровская, д. 3, кв. 7',  '+7 (977) 444-55-66','2026-03-10',true),
 (5,'П-000005','Громов',   'Артём',    'Игоревич',    '1969-05-09','М','456-789-012 34','7701234500000005',NULL,        'г. Москва, ул. Чертановская, д. 40, кв. 88',    '+7 (985) 555-66-77','2024-06-01',true),
 (6,'П-000006','Белова',   'Софья',    'Михайловна',  '1995-09-17','Ж','567-890-123 45','7701234500000006','ДМС-100206','г. Москва, ул. Красного Маяка, д. 9, кв. 34',   '+7 (999) 666-77-88','2026-04-22',true),
 (7,'П-000007','Мельников','Егор',     'Алексеевич',  '1988-12-25','М',NULL,            '7701234500000007',NULL,        'г. Москва, Симферопольский б-р, д. 20, кв. 2',  '+7 (916) 777-88-99','2026-05-05',true),
 (8,'П-000008','Тихонова', 'Валерия',  'Романовна',   '1999-04-04','Ж','678-901-234 56','7701234500000008',NULL,        'г. Москва, ул. Цюрупы, д. 15, кв. 61',          '+7 (926) 888-99-00','2026-06-18',true),
 (9,'П-000009','Ковалёв',  'Николай',  'Петрович',    '1957-08-19','М','789-012-345 67','7701234500000009',NULL,        'г. Москва, Балаклавский пр-т, д. 32, кв. 150',  '+7 (495) 999-00-11','2023-09-12',true),
 (10,'П-000010','Романова','Екатерина','Олеговна',    '1983-02-11','Ж','890-123-456 78','7701234500000010','ДМС-100210','г. Москва, ул. Наметкина, д. 7, кв. 23',        '+7 (903) 000-11-22','2026-07-30',true);

-- Хеши — заглушки. Для реальных паролей генерируйте BCrypt в приложении.
INSERT INTO account (id, login, password_hash, role_id, employee_id, patient_id, is_active, last_login) VALUES
 (1, 'admin',     crypt('demo123', gen_salt('bf')), 1, 8,    NULL, true, '2026-09-28 09:00'),
 (2, 'sokolov',   crypt('demo123', gen_salt('bf')), 2, 1,    NULL, true, '2026-09-28 08:10'),
 (3, 'ivanova',   crypt('demo123', gen_salt('bf')), 2, 2,    NULL, true, '2026-09-28 08:45'),
 (4, 'kuznetsov', crypt('demo123', gen_salt('bf')), 2, 3,    NULL, true, '2026-09-27 09:55'),
 (5, 'morozova',  crypt('demo123', gen_salt('bf')), 2, 4,    NULL, true, '2026-09-25 08:50'),
 (6, 'volkov',    crypt('demo123', gen_salt('bf')), 2, 5,    NULL, true, '2026-09-25 08:55'),
 (7, 'smirnova',  crypt('demo123', gen_salt('bf')), 2, 9,    NULL, true, '2026-09-28 13:50'),
 (8, 'lebedeva',  crypt('demo123', gen_salt('bf')), 4, 6,    NULL, true, '2026-09-28 08:00'),
 (9, 'petrova',   crypt('demo123', gen_salt('bf')), 3, 7,    NULL, true, '2026-09-29 07:55'),
 (10,'kirillov',  crypt('demo123', gen_salt('bf')), 5, NULL, 1,    true, '2026-09-24 19:20'),
 (11,'zakharova', crypt('demo123', gen_salt('bf')), 5, NULL, 2,    true, '2026-09-23 20:05'),
 (12,'nikitin',   crypt('demo123', gen_salt('bf')), 5, NULL, 3,    true, '2026-09-26 12:30');

INSERT INTO schedule (id, employee_id, room_id, work_date, start_time, end_time, slot_minutes) VALUES
 (1, 2, 5,'2026-09-22','09:00','13:00',30),
 (2, 3, 6,'2026-09-22','10:00','15:00',30),
 (3, 1, 1,'2026-09-23','08:00','14:00',20),
 (4, 9, 2,'2026-09-23','14:00','19:00',20),
 (5, 4, 7,'2026-09-24','09:00','15:00',30),
 (6, 5, 3,'2026-09-25','09:00','14:00',30),
 (7, 2, 5,'2026-09-30','09:00','13:00',30),
 (8, 1, 1,'2026-09-30','08:00','14:00',20),
 (9, 3, 6,'2026-10-01','10:00','15:00',30);

INSERT INTO appointment (id, schedule_id, patient_id, start_time, status, source, created_at) VALUES
 (1, 1, 5,'09:00','завершена',    'регистратура','2026-09-15 11:20'),
 (2, 1, 9,'09:30','завершена',    'телефон',     '2026-09-16 10:05'),
 (3, 2, 6,'10:00','завершена',    'сайт',        '2026-09-18 18:40'),
 (4, 3, 1,'08:20','завершена',    'сайт',        '2026-09-20 21:10'),
 (5, 3, 2,'08:40','завершена',    'регистратура','2026-09-21 09:30'),
 (6, 4, 7,'14:20','завершена',    'приложение',  '2026-09-21 16:00'),
 (7, 5, 4,'09:00','завершена',    'сайт',        '2026-09-19 12:15'),
 (8, 6, 3,'10:00','завершена',    'регистратура','2026-09-22 15:45'),
 (9, 4, 8,'14:40','неявка',       'телефон',     '2026-09-22 10:30'),
 (10,6,10,'10:30','отменена',     'приложение',  '2026-09-23 19:00'),
 (11,7, 9,'09:00','запланирована','регистратура','2026-09-22 10:20'),
 (12,8, 3,'08:00','запланирована','сайт',        '2026-09-26 14:25'),
 (13,8, 6,'08:20','запланирована','приложение',  '2026-09-27 20:10'),
 (14,9, 6,'10:00','запланирована','сайт',        '2026-09-27 20:15');

INSERT INTO visit (id, appointment_id, visited_at, complaints, anamnesis, objective_status,
                   diagnosis_code, recommendations, is_closed) VALUES
 (1,1,'2026-09-22 09:05','Повышение давления по утрам, головная боль',
    'Гипертония около 5 лет, препараты принимает нерегулярно',
    'АД 158/96, ЧСС 78, тоны сердца ритмичные','I10',
    'Контроль АД дважды в день, ограничить соль, повторный приём через 2 недели', true),
 (2,2,'2026-09-22 09:35','Одышка при физической нагрузке',
    'Гипертония, курит 30 лет',
    'АД 150/90, ЧСС 82, в лёгких жёсткое дыхание','I10',
    'Отказ от курения, ЭКГ, наблюдение у кардиолога', true),
 (3,3,'2026-09-22 10:05','Периодические сильные головные боли с тошнотой',
    'Приступы 2–3 раза в месяц, у матери мигрень',
    'Неврологический статус без очаговой симптоматики','G43.9',
    'Вести дневник головной боли, режим сна, МРТ головного мозга', true),
 (4,4,'2026-09-23 08:25','Кашель, насморк, температура 37,8',
    'Заболел 2 дня назад, контакт с больным ОРВИ',
    'Зев гиперемирован, дыхание везикулярное','J06.9',
    'Обильное питьё, постельный режим, жаропонижающие при t > 38,5', true),
 (5,5,'2026-09-23 08:45','Боль в эпигастрии после еды, изжога',
    'Симптомы около месяца, нерегулярное питание',
    'Живот мягкий, болезненный в эпигастрии','K29.7',
    'Диета, отказ от острого и кофе, приём омепразола 14 дней', true),
 (6,6,'2026-09-23 14:25','Кашель с мокротой 5 дней',
    'Переохлаждение на прошлой неделе',
    'Температура 37,4, в лёгких сухие хрипы','J20.9',
    'Муколитики, антибиотик, рентген грудной клетки', true),
 (7,7,'2026-09-24 09:05','Ухудшение зрения вдаль',
    'Носит очки, последняя проверка 2 года назад',
    'Острота зрения OD 0,4 / OS 0,5, глазное дно без патологии','H52.1',
    'Коррекция очками, капли, контроль через год', true),
 (8,8,'2026-09-25 10:05','Боли в пояснице после нагрузки',
    'Сидячая работа, боль 2 недели',
    'Болезненность паравертебральных точек, движения ограничены','M54.5',
    'Ограничить нагрузку, НПВС при боли, ЛФК', true);

INSERT INTO invoice (id, patient_id, created_at, status, method_id, paid_at) VALUES
 (1, 5,'2026-09-22 10:00','оплачен',   2,'2026-09-22 10:05'),
 (2, 9,'2026-09-22 10:10','оплачен',   3,'2026-09-22 10:12'),
 (3, 6,'2026-09-22 10:40','оплачен',   2,'2026-09-22 10:42'),
 (4, 1,'2026-09-23 09:00','оплачен',   1,'2026-09-23 09:05'),
 (5, 2,'2026-09-23 09:15','оплачен',   2,'2026-09-23 09:20'),
 (6, 7,'2026-09-23 15:00','не оплачен',NULL,NULL),
 (7, 4,'2026-09-24 09:40','оплачен',   3,'2026-09-24 09:45'),
 (8, 3,'2026-09-25 10:40','не оплачен',NULL,NULL);

INSERT INTO visit_service (id, visit_id, service_id, invoice_id, quantity, price, rendered_at) VALUES
 (1, 1, 2,  1, 1, 2500.00,'2026-09-22 09:30'),
 (2, 1, 10, 1, 1,  900.00,'2026-09-22 09:50'),
 (3, 2, 2,  2, 1, 2500.00,'2026-09-22 10:00'),
 (4, 3, 3,  3, 1, 2400.00,'2026-09-22 10:30'),
 (5, 4, 1,  4, 1, 1800.00,'2026-09-23 08:45'),
 (6, 4, 6,  4, 1,  450.00,'2026-09-23 08:50'),
 (7, 5, 1,  5, 1, 1800.00,'2026-09-23 09:05'),
 (8, 5, 9,  5, 1,  650.00,'2026-09-23 09:10'),
 (9, 6, 1,  6, 1, 1800.00,'2026-09-23 14:45'),
 (10,6, 6,  6, 1,  450.00,'2026-09-23 14:55'),
 (11,7, 4,  7, 1, 2200.00,'2026-09-24 09:30'),
 (12,7, 14, 7, 1,  600.00,'2026-09-24 09:35'),
 (13,8, 5,  8, 1, 2300.00,'2026-09-25 10:35');

INSERT INTO referral (id, visit_id, service_id, status, executor_id, done_at, result) VALUES
 (1,1,10,'выполнено',6,'2026-09-22 09:50','Синусовый ритм, ЧСС 76, признаки гипертрофии левого желудочка'),
 (2,2,10,'выдано',   NULL,NULL,NULL),
 (3,3,13,'выдано',   NULL,NULL,NULL),
 (4,4,6, 'выполнено',6,'2026-09-23 08:50','Лейкоциты 9,8·10⁹/л, СОЭ 18 мм/ч'),
 (5,5,9, 'выполнено',6,'2026-09-23 09:10','Положительный'),
 (6,6,6, 'выполнено',6,'2026-09-23 14:55','Лейкоциты 11,2·10⁹/л, СОЭ 24 мм/ч'),
 (7,6,12,'выдано',   NULL,NULL,NULL),
 (8,8,13,'отменено', NULL,NULL,NULL);

INSERT INTO prescription (id, visit_id, drug_id, dosage, instruction, is_recipe) VALUES
 (1, 1,3,'50 мг', 'По 1 таблетке утром ежедневно', true),
 (2, 1,4,'5 мг',  'По 1 таблетке вечером ежедневно', true),
 (3, 2,4,'5 мг',  'По 1 таблетке 1 раз в день', true),
 (4, 3,5,'50 мг', 'При приступе 1 таблетка, повторно не ранее чем через 2 часа', true),
 (5, 4,2,'500 мг','При температуре выше 38,5, до 3 раз в сутки', false),
 (6, 5,6,'20 мг', 'По 1 капсуле за 30 минут до завтрака, 14 дней', true),
 (7, 6,7,'30 мг', 'По 1 таблетке 3 раза в день после еды, 7 дней', false),
 (8, 6,1,'500 мг','По 1 таблетке 3 раза в день, 7 дней', true),
 (9, 7,9,'4%',    'По 2 капли 3 раза в день в оба глаза', false),
 (10,8,8,'400 мг','По 1 таблетке до 3 раз в день после еды при боли', false);

INSERT INTO audit (id, account_id, patient_id, acted_at, action, table_name, record_id) VALUES
 (1,9, 5,   '2026-09-22 08:55','INSERT','appointment',1),
 (2,3, 5,   '2026-09-22 09:05','INSERT','visit',1),
 (3,3, 5,   '2026-09-22 09:25','UPDATE','visit',1),
 (4,9, 5,   '2026-09-22 10:00','INSERT','invoice',1),
 (5,2, 1,   '2026-09-23 08:25','INSERT','visit',4),
 (6,1, NULL,'2026-09-24 09:10','UPDATE','account',8),
 (7,10,1,   '2026-09-24 19:20','SELECT','visit',4);

-- ---------------------------------------------------------------------
--  Синхронизация счётчиков identity после вставки с явными id
-- ---------------------------------------------------------------------
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['specialty','post','room','role','service_group','pay_method',
      'drug','service','employee','patient','account','schedule','appointment','visit',
      'invoice','visit_service','referral','prescription','audit']
  LOOP
    EXECUTE format('SELECT setval(pg_get_serial_sequence(%L, %L), COALESCE(MAX(id), 1)) FROM %I',
                   t, 'id', t);
  END LOOP;
END $$;

-- Права на сохранение темы для локального Desktop-просмотра.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'clinic_preview') THEN
        GRANT SELECT, INSERT ON user_theme TO clinic_preview;
        GRANT UPDATE (theme, updated_at) ON user_theme TO clinic_preview;
    END IF;
END $$;
